from pathlib import Path
import sys

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.serving.load_outputs import (
    read_match_predictions,
    read_coverage_summary,
    read_model_leaderboard,
    read_observed_match_results,
    read_team_summary,
)

st.set_page_config(page_title="World Cup Forecasting Lab", layout="wide")

SERVING_DIR = ROOT / "data" / "serving"


def _load_outputs() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    return (
        read_model_leaderboard(SERVING_DIR),
        read_match_predictions(SERVING_DIR),
        read_team_summary(SERVING_DIR),
        read_coverage_summary(SERVING_DIR),
        read_observed_match_results(SERVING_DIR),
    )


def _render_empty_state(message: str) -> None:
    st.info(message)


def _render_dataframe(frame: pd.DataFrame, empty_message: str) -> None:
    if frame.empty:
        _render_empty_state(empty_message)
        return
    st.dataframe(frame, use_container_width=True, hide_index=True)


def _count_observed_matches(observed_results: pd.DataFrame) -> int:
    if observed_results.empty:
        return 0
    if "match_id" in observed_results.columns:
        return int(observed_results["match_id"].nunique())
    return len(observed_results)


def _render_home(
    leaderboard: pd.DataFrame,
    predictions: pd.DataFrame,
    teams: pd.DataFrame,
    coverage: pd.DataFrame,
    observed_results: pd.DataFrame,
) -> None:
    st.title("World Cup Forecasting Lab")
    st.write(
        "A real-data-only public app for exploring model outputs, observed match truth, "
        "and team summaries generated by the serving pipeline."
    )
    st.caption("real-data-only public layer with explicit source coverage")

    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("Observed Matches", _count_observed_matches(observed_results))
    col2.metric("Coverage Metrics", len(coverage))
    col3.metric("Leaderboard Rows", len(leaderboard))
    col4.metric("Forecasted Matches", len(predictions))
    col5.metric("Teams Profiled", len(teams))

    if not observed_results.empty:
        st.success("Observed match truth is loaded from real data and available for review below.")
        _render_dataframe(
            observed_results,
            "Observed match truth is expected here when completed matches have been collected.",
        )
    else:
        _render_empty_state(
            "No real observed match truth is available yet. Run the serving pipeline after "
            "completed matches are ingested so the public app stays real-data-only."
        )

    if coverage.empty:
        _render_empty_state(
            "Coverage Summary is not available yet. Run the serving pipeline with real observed "
            "match truth so the app can explain what has been validated."
        )


def _render_model_leaderboard(leaderboard: pd.DataFrame) -> None:
    st.subheader("Model Leaderboard")
    st.write("Track model-level evaluation outputs backed by real observed match truth.")
    _render_dataframe(
        leaderboard,
        "No leaderboard is published yet because there is not enough real observed match truth "
        "to support a public comparison.",
    )


def _render_match_explorer(predictions: pd.DataFrame) -> None:
    st.subheader("Match Explorer")
    st.write("Browse match-level forecasts alongside a public contract that only uses real data.")
    _render_dataframe(
        predictions,
        "No match forecasts are published yet. The public app only exposes forecasts that can be "
        "paired with real observed match truth and coverage metadata.",
    )


def _render_coverage_summary(coverage: pd.DataFrame) -> None:
    st.subheader("Coverage Summary")
    st.write(
        "Review which targets currently have real observed match truth and how much public "
        "coverage is available for each one."
    )
    _render_dataframe(
        coverage,
        "Coverage Summary is not available yet. Run the serving pipeline with real observed "
        "match truth to publish target-level coverage.",
    )


def _render_teams(teams: pd.DataFrame) -> None:
    st.subheader("Teams")
    st.write("Review team-level summary outputs generated from the real-data-only serving layer.")
    _render_dataframe(
        teams,
        "No team summary is published yet because the real observed match truth layer has not "
        "produced a public team view.",
    )


def _render_methodology() -> None:
    st.subheader("Methodology")
    st.write(
        "This app reads precomputed serving outputs instead of fitting models live in the "
        "UI. That keeps the experience stable while leaving training, evaluation, and batch "
        "forecast generation in the pipeline layer."
    )
    st.markdown(
        """
        - The public app is real-data-only: it only surfaces artifacts tied to real observed match truth.
        - `Coverage Summary` shows what has true observed coverage today versus what is still missing.
        - `Home` highlights observed matches first so the public status reflects truth coverage, not file presence.
        - `Model Leaderboard` is intended for model comparison artifacts.
        - `Match Explorer` is intended for match-level prediction rows.
        - `Teams` is intended for team summary outputs used in storytelling.
        - Empty states explain missing real observed match truth rather than implying generic missing CSV errors.
        """
    )


def main() -> None:
    leaderboard, predictions, teams, coverage, observed_results = _load_outputs()
    home_tab, coverage_tab, leaderboard_tab, match_tab, teams_tab, methodology_tab = st.tabs(
        ["Home", "Coverage Summary", "Model Leaderboard", "Match Explorer", "Teams", "Methodology"]
    )

    with home_tab:
        _render_home(leaderboard, predictions, teams, coverage, observed_results)

    with coverage_tab:
        _render_coverage_summary(coverage)

    with leaderboard_tab:
        _render_model_leaderboard(leaderboard)

    with match_tab:
        _render_match_explorer(predictions)

    with teams_tab:
        _render_teams(teams)

    with methodology_tab:
        _render_methodology()


main()
