from pathlib import Path
import sys

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.serving.load_outputs import (
    read_match_predictions,
    read_model_leaderboard,
    read_team_summary,
)

st.set_page_config(page_title="World Cup Forecasting Lab", layout="wide")

SERVING_DIR = ROOT / "data" / "serving"


def _load_outputs() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    return (
        read_model_leaderboard(SERVING_DIR),
        read_match_predictions(SERVING_DIR),
        read_team_summary(SERVING_DIR),
    )


def _render_empty_state(message: str) -> None:
    st.info(message)


def _render_dataframe(frame: pd.DataFrame, empty_message: str) -> None:
    if frame.empty:
        _render_empty_state(empty_message)
        return
    st.dataframe(frame, use_container_width=True, hide_index=True)


def _render_home(
    leaderboard: pd.DataFrame, predictions: pd.DataFrame, teams: pd.DataFrame
) -> None:
    st.title("World Cup Forecasting Lab")
    st.write(
        "A lightweight public-facing shell for exploring model outputs, match-level "
        "forecasts, and team summaries generated by the serving pipeline."
    )

    col1, col2, col3 = st.columns(3)
    col1.metric("Leaderboard Rows", len(leaderboard))
    col2.metric("Forecasted Matches", len(predictions))
    col3.metric("Teams Profiled", len(teams))

    if leaderboard.empty and predictions.empty and teams.empty:
        _render_empty_state(
            "Serving outputs are not available yet. Add CSVs under "
            "`data/serving/` to populate the forecasting tabs."
        )


def _render_model_leaderboard(leaderboard: pd.DataFrame) -> None:
    st.subheader("Model Leaderboard")
    st.write("Track model-level evaluation outputs once serving artifacts are available.")
    _render_dataframe(
        leaderboard,
        "No model leaderboard CSV was found yet. Expected `data/serving/model_leaderboard.csv`.",
    )


def _render_match_explorer(predictions: pd.DataFrame) -> None:
    st.subheader("Match Explorer")
    st.write("Browse match-level forecasts and filter the table when predictions are present.")
    _render_dataframe(
        predictions,
        "No match predictions CSV was found yet. Expected `data/serving/match_predictions.csv`.",
    )


def _render_teams(teams: pd.DataFrame) -> None:
    st.subheader("Teams")
    st.write("Review team-level summary outputs generated by the forecasting pipeline.")
    _render_dataframe(
        teams,
        "No team summary CSV was found yet. Expected `data/serving/team_summary.csv`.",
    )


def _render_methodology() -> None:
    st.subheader("Methodology")
    st.write(
        "This app reads precomputed serving outputs instead of fitting models live in the "
        "UI. That keeps the experience stable while leaving training, evaluation, and batch "
        "forecast generation in the pipeline layer."
    )
    st.markdown(
        """
        - `Model Leaderboard` is intended for model comparison artifacts.
        - `Match Explorer` is intended for match-level prediction rows.
        - `Teams` is intended for team summary outputs used in storytelling.
        - Missing CSVs degrade gracefully to notices so the public app does not crash.
        """
    )


def main() -> None:
    leaderboard, predictions, teams = _load_outputs()
    home_tab, leaderboard_tab, match_tab, teams_tab, methodology_tab = st.tabs(
        ["Home", "Model Leaderboard", "Match Explorer", "Teams", "Methodology"]
    )

    with home_tab:
        _render_home(leaderboard, predictions, teams)

    with leaderboard_tab:
        _render_model_leaderboard(leaderboard)

    with match_tab:
        _render_match_explorer(predictions)

    with teams_tab:
        _render_teams(teams)

    with methodology_tab:
        _render_methodology()


main()
